"""initial schema — users, people, notes

Revision ID: d516f4d84be9
Revises: 
Create Date: 2026-03-31 19:27:15.576888

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd516f4d84be9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('people',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=False),
    sa.Column('twitter_handle', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('how_we_met', sa.Text(), nullable=False),
    sa.Column('profile_image_url', sa.String(length=500), nullable=False),
    sa.Column('birthday', sa.String(length=20), nullable=False),
    sa.Column('anniversary', sa.String(length=20), nullable=False),
    sa.Column('met_at', sa.String(length=20), nullable=False),
    sa.Column('tags_csv', sa.Text(), nullable=False),
    sa.Column('next_follow_up', sa.String(length=20), nullable=False),
    sa.Column('follow_up_frequency_days', sa.Integer(), nullable=False),
    sa.Column('relationship_score', sa.Float(), nullable=False),
    sa.Column('relationship_status', sa.String(length=20), nullable=False),
    sa.Column('last_interaction_at', sa.String(length=30), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_user_id'), 'people', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_person_id'), 'notes', ['person_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_person_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_people_user_id'), table_name='people')
    op.drop_table('people')
    op.drop_table('users')
    # ### end Alembic commands ###
